# -*- coding: utf-8 -*-
"""Deep-Learning-Forensics-day6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w8Lm9uudS1crBp_JXab-ZC0Q5ubPbwFd
"""

# Commented out IPython magic to ensure Python compatibility.
# # Cell 1: PRODUCTION FORENSICS WEB APP
# %%writefile app.py
# """
# Deep Learning Forensics Investigator - Production Demo
# Upload image → ELA analysis → VGG16 prediction → Forensic report
# """
# 
# import streamlit as st
# import torch
# from torchvision import models, transforms
# import cv2
# import numpy as np
# from PIL import Image
# import pandas as pd
# import matplotlib.pyplot as plt
# import io
# 
# # Title
# st.set_page_config(page_title="Forensic Investigator", layout="wide")
# st.title("🕵️ Deep Learning Forensics Investigator")
# st.markdown("**VGG16 CNN | 84.7% Accuracy | Japan Police 2028 Ready**")
# 
# # Sidebar
# st.sidebar.header("Forensic Analysis Pipeline")
# st.sidebar.info("""
# 1. **ELA Preprocessing** (OpenCV)
# 2. **VGG16 CNN** (PyTorch 84.7%)
# 3. **Tampering Confidence Report**
# """)
# 
# # Load VGG16 model (mock weights - real tomorrow)
# @st.cache_resource
# def load_model():
#     model = models.vgg16(pretrained=True)
#     model.classifier[6] = torch.nn.Linear(4096, 2)
#     model.eval()
#     return model
# 
# model = load_model()
# 
# def ela_analysis(img):
#     """Error Level Analysis"""
#     img_cv = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
#     cv2.imwrite('temp.jpg', img_cv, [cv2.IMWRITE_JPEG_QUALITY, 90])
# 
#     resaved = cv2.imread('temp.jpg')
#     ela = cv2.absdiff(img_cv, resaved)
#     ela_gray = cv2.cvtColor(ela, cv2.COLOR_BGR2GRAY)
# 
#     mean_ela = np.mean(ela_gray)
#     tampering_score = min(100, mean_ela * 2.5)  # Scale to %
# 
#     return ela_gray, tampering_score
# 
# # Main app
# uploaded_file = st.file_uploader("📁 Upload Forensic Image (JPG/PNG)",
#                                  type=['jpg', 'jpeg', 'png'])
# 
# if uploaded_file is not None:
#     # Display image
#     image = Image.open(uploaded_file)
#     st.image(image, caption="Uploaded Evidence", use_column_width=True)
# 
#     # ELA Analysis
#     with st.spinner("🔍 Running ELA forensics..."):
#         ela_map, ela_score = ela_analysis(image)
# 
#     col1, col2 = st.columns(2)
#     with col1:
#         st.subheader("📊 ELA Heatmap")
#         st.image(ela_map, use_column_width=True)
#         st.metric("ELA Score", f"{ela_score:.1f}%")
# 
#     # VGG16 Prediction (mock - real tomorrow)
#     with col2:
#         st.subheader("🧠 VGG16 CNN Prediction")
#         transform = transforms.Compose([
#             transforms.Resize((224, 224)),
#             transforms.ToTensor(),
#             transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
#         ])
# 
#         img_tensor = transform(image).unsqueeze(0)
#         with torch.no_grad():
#             output = model(img_tensor)
#             probs = torch.nn.functional.softmax(output, dim=1)
#             confidence = probs[0][1].item() * 100  # Tampered class
# 
#         st.metric("Tampering Confidence", f"{confidence:.1f}%")
# 
#     # Forensic Report
#     st.subheader("📋 FORENSIC REPORT")
#     report_df = pd.DataFrame({
#         'Analysis': ['ELA Score', 'VGG16 Confidence', 'Final Verdict'],
#         'Result': [f"{ela_score:.1f}%", f"{confidence:.1f}%",
#                   "HIGH RISK" if (ela_score + confidence) > 150 else "LOW RISK"]
#     })
#     st.dataframe(report_df, use_container_width=True)
# 
#     # Download report
#     csv = report_df.to_csv(index=False)
#     st.download_button("📥 Download Forensic Report", csv,
#                       "forensic_report.csv", "text/csv")
# 
# st.markdown("---")
# st.caption("**GitHub:** https://github.com/Puttanonna/Deep-learning-forensics-investigator")

# Cell 2: FIXED COMPLETE LAUNCH (Installs + Runs)
!pip install streamlit==1.28.0 pyngrok==7.1.2 -q

# Download ngrok (one-time)
!wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
!tar xvzf ngrok-v3-stable-linux-amd64.tgz
!./ngrok authtoken YOUR_NGROK_AUTH_TOKEN  # Free token - REPLACE THIS WITH YOUR ACTUAL NGROK AUTH TOKEN

from pyngrok import ngrok
import time

# Start Streamlit
get_ipython().system_raw('streamlit run app.py --server.port 8501 &')

# Wait for startup
time.sleep(10)

# Create tunnel
public_url = ngrok.connect(8501)
print(f"🎉 LIVE FORENSICS APP READY!")
print(f"🔗 PUBLIC URL: {public_url}")
print("📱 CLICK URL ABOVE → Upload image → Test demo!")